#!/bin/sh

recover_rootmnt()
{
    mount --move ${1} ${rootmnt} || mount -o move ${1} ${rootmnt}
    if [ $? -ne 0 ]; then
       panic "${progname}: failed to recover root filesystem to '${rootmnt}'"
    fi
}

lock_device()
{
    local device

    case "${1}" in
        UUID=*)
            device=$(blkid -U "${1#UUID=}") ;;
        LABEL=*)
            device=$(blkid -L "${1#LABEL=}") ;;
        *)
            device=${1} ;;
    esac

    if [ "x${device}" = "x" ]; then
        log_warning_msg "${progname}: failed to look up device for ${1}"
        return 1
    fi

    if ! blockdev --setro "${device}"; then
        log_warning_msg "${progname}: failed to set device '${device}' read-only"
        return 2
    fi

    return 0
}

case "$1" in
    prereqs)
    	echo ""
    	exit 0 ;;
esac

. /scripts/functions

progname="lockroot"
config_file="${rootmnt}/etc/lockroot.conf"
nolock_file="${rootmnt}/nolock"

nolock=
for param in $(cat /proc/cmdline); do
    case ${param} in
        nolock)
            nolock=true ;;
    esac
done

if [ "x${nolock}" = "xtrue" ]; then
    log_warning_msg "${progname}: disabled, found kernel boot parameter 'nolock'"
    exit 0
fi

if [ -e "${nolock_file}" ]; then
    log_warning_msg "${progname}: disabled, found file '${nolock_file}'"
    exit 0
fi

if [ -e "${config_file}" ]; then
    while IFS= read -r line; do
        case "x$(echo ${line})" in
            x | x\#*)
                continue ;;
        esac

        case "${line}" in
            LOCKROOT_SWAP=*)
                lockroot_swap=${line#LOCKROOT_SWAP=} ;;
            LOCKROOT_LOCK=*)
                lockroot_lock=$(IFS=','; echo ${line#LOCKROOT_LOCK=}) ;;
            *=*)
                echo "${progname}: unknown configuration paramter '${line%=*}'" ;;
            *)
                echo "${progname}: invalid line '${line}'" ;;
        esac
    done < ${config_file}
fi

ovl_mount=/mnt/overlay
ovl_base=/.lock
ovl_upper=${ovl_base}/rw
ovl_lower=${ovl_base}/ro
ovl_work=${ovl_base}/.work

[ -d ${ovl_base} ] || mkdir -p ${ovl_base}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to create '${ovl_base}'"
    exit 0
fi

mount -t tmpfs tmpfs-root ${ovl_base}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to create tmpfs for root filesystem"
    exit 0
fi

[ -d ${ovl_upper} ] || mkdir -p ${ovl_upper}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to create '${ovl_upper}'"
    exit 0
fi

[ -d ${ovl_lower} ] || mkdir -p ${ovl_lower}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to create '${ovl_lower}'"
    exit 0
fi

[ -d ${ovl_work} ] || mkdir -p ${ovl_work}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to create '${ovl_work}'"
    exit 0
fi

mount --move ${rootmnt} ${ovl_lower} || mount -o move ${rootmnt} ${ovl_lower}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to move root filesystem from '${rootmnt}' to '${ovl_lower}'"
    exit 0
fi

[ -d ${ovl_mount} ] || mkdir -p ${ovl_mount}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to create '${ovl_mount}'"
    recover_rootmnt "${ovl_lower}"
    exit 0
fi

mount -t overlay -o lowerdir=${ovl_lower},upperdir=${ovl_upper},workdir=${ovl_work} overlay-root ${ovl_mount}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to create overlay for root filesystem"
    recover_rootmnt "${ovl_lower}"
    exit 0
fi

[ -d ${ovl_mount}${ovl_base} ] || mkdir -p ${ovl_mount}${ovl_base}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to create '${ovl_mount}${ovl_base}'"
    recover_rootmnt "${ovl_lower}"
    exit 0
fi

mount --move ${ovl_base} ${ovl_mount}${ovl_base} || mount -o move ${ovl_base} ${ovl_mount}${ovl_base}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to move '${ovl_base}' to '${ovl_mount}${ovl_base}'"
    recover_rootmnt "${ovl_lower}"
    exit 0
fi

fstab_system=${ovl_mount}${ovl_lower}/etc/fstab
fstab_overlay=${ovl_mount}/etc/fstab

cat <<EOF >${fstab_overlay}
#
#  modified by lockroot at startup
#
EOF

grep -v '^[[:blank:]]*\(#\|$\)' ${fstab_system} |
while IFS= read -r entry; do
    echo "${entry}" | read -r source target fstype mntopts

    if [ "x${target}" = "x/" ]; then
        echo "#${entry}"
        continue
    fi

    if [ "x${fstype}" = "xswap" ]; then
        if [ "x${lockroot_swap}" != "xon" ]; then
            echo "#${entry}"
        else
            echo "${entry}"
        fi
    fi

    for device in ${lockroot_lock}; do
        if [ "${device}" = "${source}" ]; then
            mntopts=$(echo "${mntopts}" | sed 's/\(rw,\)\|\(,rw\)\|\(^rw$\)//')
            if [ "x${mntopts}" != "x" ]; then
                mntopts="ro,${mntopts}"
            else
                mntopts="ro"
            fi
        fi
    done
done > ${fstab_overlay}

mount --move ${ovl_mount} ${rootmnt} || mount -o move ${ovl_mount} ${rootmnt}
if [ ${?} -ne 0 ]; then
    log_failure_msg "${progname}: failed to move '${ovl_mount}' to '${rootmnt}'"
    recover_rootmnt "${ovl_mount}${ovl_lower}"
    exit 0
fi

log_success_msg "${progname}: sucessfully set up overlay for root filesystem"

exit 0